import type { AgeBand, FactItem } from "../types";
import { pick } from "../rng";

interface FactEntry extends FactItem {
  bands: AgeBand[];
}

const FACTS: FactEntry[] = [
  { bands: ["4-6"], fact: "A group of flamingos is called a flamboyance.", extra: "They get their pink color from the food they eat." },
  { bands: ["4-6"], fact: "Otters hold hands when they sleep so they don’t drift apart.", extra: "Scientists call that a raft of otters." },
  { bands: ["4-6"], fact: "Honey never spoils. Jars thousands of years old can still be eaten.", extra: "Bees are tiny chemists." },
  { bands: ["4-6"], fact: "A banana is a berry, but a strawberry is not.", extra: "Botanists have surprising rules." },
  { bands: ["4-6", "7-9"], fact: "Octopuses have three hearts and blue blood.", extra: "Two hearts pump to the gills; one pumps to the body." },
  { bands: ["4-6", "7-9"], fact: "Wombat poop is cube-shaped.", extra: "The cubes stack and don’t roll away from their burrows." },
  { bands: ["4-6", "7-9"], fact: "Snails can sleep for up to three years.", extra: "They seal their shells and wait for rain." },
  { bands: ["4-6"], fact: "A day on Venus is longer than a year on Venus.", extra: "It spins very slowly, but races around the Sun." },
  { bands: ["4-6", "7-9"], fact: "Butterflies taste with their feet.", extra: "That’s how they know if a leaf is good for laying eggs." },
  { bands: ["4-6"], fact: "Cows have best friends and get stressed when they’re apart.", extra: "Farmers notice they stand together." },
  { bands: ["7-9"], fact: "The tongue print of a person is unique, like a fingerprint.", extra: "Don’t lick the paper to check." },
  { bands: ["7-9", "10-12"], fact: "There are more trees on Earth than stars in the Milky Way.", extra: "About three trillion trees; a few hundred billion stars in our galaxy." },
  { bands: ["7-9", "10-12"], fact: "A teaspoon of honey is the life’s work of about twelve bees.", extra: "Say thanks next time you drizzle it on toast." },
  { bands: ["7-9"], fact: "Sharks have been around longer than trees.", extra: "Early sharks swam about 400 million years ago; trees came later." },
  { bands: ["7-9", "10-12"], fact: "Your bones are about five times stronger than steel, by weight.", extra: "They’re also alive and rebuild themselves." },
  { bands: ["7-9"], fact: "A bolt of lightning is five times hotter than the surface of the Sun.", extra: "That’s why it can fuse sand into glass." },
  { bands: ["7-9", "10-12"], fact: "The Eiffel Tower grows about 6 inches taller in summer.", extra: "Heat makes the iron expand." },
  { bands: ["7-9"], fact: "Koalas have fingerprints almost identical to humans.", extra: "They’ve even confused crime-scene tape in training exercises." },
  { bands: ["7-9", "10-12"], fact: "One hummingbird egg is smaller than a jellybean.", extra: "The chick hatches in about two weeks." },
  { bands: ["10-12"], fact: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.", extra: "The pyramid is ~4,500 years old; Cleopatra died in 30 BCE." },
  { bands: ["10-12"], fact: "If you could fold a paper in half 42 times, it would reach the Moon.", extra: "Each fold doubles the thickness. Paper usually rips around seven." },
  { bands: ["10-12"], fact: "Oxford University is older than the Aztec Empire.", extra: "Teaching at Oxford began around 1096; Tenochtitlán was founded in 1325." },
  { bands: ["10-12"], fact: "A day on Earth used to last only about 22 hours.", extra: "The Moon’s gravity is slowly stretching our days." },
  { bands: ["10-12"], fact: "Bananas are slightly radioactive because they contain potassium-40.", extra: "You’d need to eat millions for it to matter. Eat the banana." },
  { bands: ["10-12"], fact: "The fingerprints of a koala are so close to ours that they can confuse detectives.", extra: "Marsupials and primates arrived at the same trick separately." },
  { bands: ["4-6", "7-9"], fact: "Sea otters have the thickest fur of any mammal.", extra: "Up to a million hairs per square inch keep them warm." },
  { bands: ["4-6"], fact: "Penguins propose with pebbles.", extra: "A smooth stone is a high compliment." },
  { bands: ["7-9", "10-12"], fact: "The shortest war in history lasted 38 minutes.", extra: "It was fought in 1896 between Britain and Zanzibar." },
  { bands: ["10-12"], fact: "Your stomach gets a new lining every few days.", extra: "Otherwise it would digest itself." },
  { bands: ["4-6", "7-9"], fact: "A snail can have about 14,000 teeth.", extra: "They sit on a tiny ribbon called a radula." },
  { bands: ["7-9"], fact: "The inventor of the Pringles can is buried in one.", extra: "Fredric Baur’s ashes went into a can of his own design." },
  { bands: ["10-12"], fact: "There’s a species of jellyfish that can reverse its life cycle.", extra: "Turritopsis dohrnii can return to a younger stage when stressed." },
  { bands: ["4-6"], fact: "Sloths can hold their breath longer than dolphins — over 40 minutes.", extra: "They slow their hearts to do it." },
  { bands: ["7-9", "10-12"], fact: "Hot water can freeze faster than cold water in some conditions.", extra: "It’s called the Mpemba effect. Scientists still argue why." },
  { bands: ["4-6", "7-9"], fact: "A cloud can weigh as much as 100 elephants.", extra: "The water is spread out as tiny droplets, so it floats." },
  { bands: ["10-12"], fact: "Time passes a tiny bit faster for your head than for your feet.", extra: "Earth’s gravity slows clocks — GPS satellites correct for this." },
  { bands: ["7-9", "10-12"], fact: "Most of the oxygen you breathe comes from ocean plankton, not just forests.", extra: "Tiny cyanobacteria and algae do a huge share of photosynthesis." },
  { bands: ["4-6"], fact: "Your tongue print is as unique as your fingerprint.", extra: "Nobody else has one quite like yours." },
  { bands: ["7-9"], fact: "The first computer bug was a real moth.", extra: "It was taped into a logbook in 1947 after it jammed a relay." },
  { bands: ["10-12"], fact: "A light-year is a distance, not a time — about 6 trillion miles.", extra: "It’s how far light travels in one Earth year." },
  { bands: ["4-6"], fact: "A baby kangaroo is about the size of a jellybean when it is born.", extra: "It crawls into its mother’s pouch to keep growing." },
  { bands: ["4-6"], fact: "Elephants are the only animals that can’t jump.", extra: "Their legs are built for walking, not leaping." },
  { bands: ["4-6"], fact: "A group of lions is called a pride.", extra: "The lionesses usually do most of the hunting." },
  { bands: ["4-6"], fact: "Frogs drink water through their skin.", extra: "They don’t need to take a sip with their mouths." },
  { bands: ["4-6"], fact: "A duck’s quack echoes like any other sound.", extra: "People used to think it didn’t, but that’s a myth." },
  { bands: ["4-6"], fact: "Rabbits can see almost all the way around their heads.", extra: "Their eyes are on the sides to spot danger." },
  { bands: ["4-6"], fact: "A starfish can grow a new arm if it loses one.", extra: "Some can even grow a whole new body from one arm." },
  { bands: ["4-6"], fact: "Bees dance to tell each other where flowers are.", extra: "It’s called the waggle dance." },
  { bands: ["4-6"], fact: "A giraffe’s tongue can be about 18 inches long.", extra: "It’s dark blue-purple, which may protect it from sunburn." },
  { bands: ["4-6"], fact: "Polar bears have black skin under their white fur.", extra: "The dark skin helps them soak up the sun’s warmth." },
  { bands: ["4-6"], fact: "A chameleon can move its two eyes in different directions.", extra: "It can look forward and backward at the same time." },
  { bands: ["4-6"], fact: "Owls can turn their heads about three-quarters of the way around.", extra: "They can’t move their eyes, so they turn their necks instead." },
  { bands: ["4-6"], fact: "A snail moves by making a trail of slime.", extra: "The slime helps it glide over rough ground." },
  { bands: ["4-6"], fact: "Ants can lift many times their own body weight.", extra: "For their size, they are super strong." },
  { bands: ["4-6"], fact: "The Sun is so big that about a million Earths could fit inside it.", extra: "It’s a giant ball of glowing gas." },
  { bands: ["4-6"], fact: "Our Moon has no air, so there is no wind or sound there.", extra: "Astronauts’ footprints can stay for a very long time." },
  { bands: ["4-6"], fact: "A rainbow is made when sunlight shines through raindrops.", extra: "The drops split the light into different colors." },
  { bands: ["4-6"], fact: "Spiders are not insects — they have eight legs.", extra: "Insects have six legs; spiders belong to a group called arachnids." },
  { bands: ["4-6"], fact: "A group of crows is called a murder.", extra: "Crows are very clever birds." },
  { bands: ["4-6", "7-9"], fact: "Camels store fat, not water, in their humps.", extra: "The fat gives them energy when food is scarce." },
  { bands: ["4-6", "7-9"], fact: "A seahorse dad, not the mom, carries the babies.", extra: "He keeps the eggs in a pouch until they hatch." },
  { bands: ["4-6", "7-9"], fact: "Dolphins sleep with one half of their brain awake.", extra: "That way they remember to come up for air." },
  { bands: ["4-6", "7-9"], fact: "A group of fish swimming together is called a school.", extra: "Swimming together helps keep them safe from predators." },
  { bands: ["4-6", "7-9"], fact: "Bats are the only mammals that can truly fly.", extra: "Their wings are made of skin stretched over long finger bones." },
  { bands: ["4-6", "7-9"], fact: "A group of owls is called a parliament.", extra: "Many owls are awake at night and sleep in the day." },
  { bands: ["4-6", "7-9"], fact: "Woodpeckers have special skulls that cushion their brains.", extra: "That’s how they can peck wood without hurting themselves." },
  { bands: ["4-6", "7-9"], fact: "A cat has a special back-of-eye layer that helps it see in the dark.", extra: "It’s why cats’ eyes seem to glow in the dark." },
  { bands: ["7-9"], fact: "The blue whale is the largest animal that has ever lived.", extra: "Its heart alone can be as big as a small car." },
  { bands: ["7-9"], fact: "A hummingbird’s heart can beat over 1,000 times a minute.", extra: "They flap their wings so fast the wings make a humming sound." },
  { bands: ["7-9"], fact: "Sound travels about four times faster in water than in air.", extra: "That’s why whales can hear each other from far away." },
  { bands: ["7-9"], fact: "Honeybees have five eyes.", extra: "Two big ones and three small ones on top of the head." },
  { bands: ["7-9"], fact: "The Great Wall of China was built over many centuries.", extra: "Different dynasties added to it across about 2,000 years." },
  { bands: ["7-9"], fact: "A crocodile cannot stick out its tongue.", extra: "The tongue is held down by a membrane on the bottom of its mouth." },
  { bands: ["7-9"], fact: "Your nose can remember thousands of different smells.", extra: "Smell is closely tied to memory in the brain." },
  { bands: ["7-9"], fact: "A group of jellyfish is called a smack.", extra: "Jellyfish have no brain, heart, or bones." },
  { bands: ["7-9"], fact: "The platypus is a mammal that lays eggs.", extra: "It also has a bill like a duck and webbed feet." },
  { bands: ["7-9"], fact: "A cheetah can go from standstill to highway speed in a few seconds.", extra: "It’s the fastest land animal, but only in short bursts." },
  { bands: ["7-9"], fact: "Sunflowers turn to face the Sun as they grow.", extra: "Young sunflowers follow the Sun across the sky each day." },
  { bands: ["7-9"], fact: "A group of frogs is called an army.", extra: "Many frogs croak loudly to call for mates." },
  { bands: ["7-9"], fact: "The human body has more than 600 muscles.", extra: "You use many of them just to smile or blink." },
  { bands: ["7-9"], fact: "Antarctica is the largest desert on Earth.", extra: "A desert is any place with very little rain, not just hot sand." },
  { bands: ["7-9"], fact: "A group of porcupines is called a prickle.", extra: "Their sharp quills help protect them from predators." },
  { bands: ["7-9", "10-12"], fact: "Sharks don’t have a single bone in their bodies.", extra: "Their skeletons are made of bendy cartilage, like your ears." },
  { bands: ["7-9", "10-12"], fact: "The heart of a shrimp is located in its head.", extra: "Their bodies are built very differently from ours." },
  { bands: ["7-9", "10-12"], fact: "A single lightning bolt can carry a huge amount of electricity.", extra: "It heats the air so fast that it makes the boom of thunder." },
  { bands: ["7-9", "10-12"], fact: "Venus is the hottest planet, even though Mercury is closer to the Sun.", extra: "Thick clouds trap heat like a blanket." },
  { bands: ["7-9", "10-12"], fact: "The Sahara Desert can get cold enough to freeze at night.", extra: "Sand doesn’t hold heat well once the Sun goes down." },
  { bands: ["7-9", "10-12"], fact: "Your body has about 100,000 miles of blood vessels.", extra: "Laid end to end, they could circle Earth several times." },
  { bands: ["7-9", "10-12"], fact: "Bamboo is one of the fastest-growing plants on Earth.", extra: "Some kinds can grow nearly a meter in a single day." },
  { bands: ["7-9", "10-12"], fact: "The Pacific Ocean is the largest ocean on Earth.", extra: "It covers about a third of the planet’s surface." },
  { bands: ["7-9", "10-12"], fact: "Lightning strikes the Earth millions of times every day.", extra: "Most strikes happen over tropical parts of the world." },
  { bands: ["7-9", "10-12"], fact: "A group of rhinos is called a crash.", extra: "Despite their size, rhinos can run surprisingly fast." },
  { bands: ["7-9", "10-12"], fact: "Saturn is so light for its size that it would float in water.", extra: "It’s mostly made of gas rather than rock." },
  { bands: ["10-12"], fact: "The Earth is about 4.5 billion years old.", extra: "Humans have only been around for a tiny slice of that time." },
  { bands: ["10-12"], fact: "It takes sunlight about 8 minutes to reach Earth.", extra: "So the light you see is always a few minutes old." },
  { bands: ["10-12"], fact: "Mount Everest is the highest point above sea level on Earth.", extra: "It’s still slowly rising as tectonic plates push together." },
  { bands: ["10-12"], fact: "The deepest part of the ocean is deeper than Everest is tall.", extra: "It’s the Mariana Trench in the Pacific Ocean." },
  { bands: ["10-12"], fact: "There are more possible chess games than atoms in the observable universe.", extra: "The number of games is almost impossibly large." },
  { bands: ["10-12"], fact: "Neutron stars are so dense that a teaspoon would weigh billions of tons.", extra: "They form when a huge star collapses." },
  { bands: ["10-12"], fact: "Jupiter is more than twice as massive as all the other planets combined.", extra: "It’s the largest planet in our solar system." },
  { bands: ["10-12"], fact: "The speed of light is about 300,000 kilometers per second.", extra: "Nothing we know of can travel faster." },
  { bands: ["10-12"], fact: "Human DNA is about 60 percent similar to a banana’s.", extra: "All living things share some of the same basic building blocks." },
  { bands: ["10-12"], fact: "The printing press was invented by Johannes Gutenberg around 1440.", extra: "It made books far cheaper and helped spread reading." },
  { bands: ["10-12"], fact: "Sound cannot travel through the vacuum of space.", extra: "There are no air molecules to carry the vibrations." },
  { bands: ["10-12"], fact: "The human brain uses about 20 percent of the body’s energy.", extra: "That’s a lot for an organ that weighs about three pounds." },
  { bands: ["10-12"], fact: "The Statue of Liberty was a gift from France to the United States.", extra: "It was dedicated in 1886 as a symbol of friendship." },
  { bands: ["10-12"], fact: "Glass is made mainly from melted sand.", extra: "Heating sand to a high temperature turns it clear and hard." },
  { bands: ["10-12"], fact: "The first photograph ever taken required many hours of exposure.", extra: "It was made by Joseph Nicéphore Niépce in the 1820s." },
  { bands: ["10-12"], fact: "There is enough gold in the ocean to give everyone several pounds.", extra: "It’s spread so thin that it can’t be collected profitably." },
  { bands: ["10-12"], fact: "A comet’s tail always points away from the Sun.", extra: "The solar wind pushes the dust and gas away from it." },
  { bands: ["10-12"], fact: "The human eye can distinguish millions of different colors.", extra: "Special cells called cones let us see in color." },
  { bands: ["10-12"], fact: "Diamonds and pencil lead are both made of pure carbon.", extra: "The atoms are just arranged in different patterns." },
  { bands: ["10-12"], fact: "The Wright brothers’ first powered flight lasted about 12 seconds.", extra: "It happened in 1903 and covered around 120 feet." },
];

export function pickFact(band: AgeBand, rng: () => number): FactItem {
  const pool = FACTS.filter((f) => f.bands.includes(band));
  const f = pick(rng, pool.length ? pool : FACTS);
  return { fact: f.fact, extra: f.extra };
}
