import type { AgeBand } from "../types";
import { pick } from "../rng";

export interface JokeItem {
  setup: string;
  punchline: string;
}

interface JokeEntry extends JokeItem {
  bands: AgeBand[];
}

const JOKES: JokeEntry[] = [
  { bands: ["4-6"], setup: "Why did the banana go to the doctor?", punchline: "It wasn’t peeling well." },
  { bands: ["4-6"], setup: "What do you call a sleepy cow?", punchline: "A bull-dozer… no, a cow-a-nap!" },
  { bands: ["4-6"], setup: "Why don’t eggs tell jokes?", punchline: "They’d crack each other up." },
  { bands: ["4-6"], setup: "What did the pancake say to the waffle?", punchline: "You’re waffle-y nice!" },
  { bands: ["4-6"], setup: "Why was the broom late?", punchline: "It over-swept." },
  { bands: ["4-6", "7-9"], setup: "What do you call cheese that isn’t yours?", punchline: "Nacho cheese." },
  { bands: ["4-6", "7-9"], setup: "Why did the cookie go to the hospital?", punchline: "It felt crumb-y." },
  { bands: ["4-6", "7-9"], setup: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
  { bands: ["4-6"], setup: "What do clouds wear under their clothes?", punchline: "Thunderwear." },
  { bands: ["4-6", "7-9"], setup: "Why did the student eat his homework?", punchline: "The teacher said it was a piece of cake." },
  { bands: ["4-6"], setup: "What’s a cat’s favorite color?", punchline: "Purr-ple." },
  { bands: ["4-6", "7-9"], setup: "Why can’t you give Elsa a balloon?", punchline: "Because she’ll let it go." },
  { bands: ["7-9"], setup: "Why did the scarecrow get a raise?", punchline: "He was outstanding in his field." },
  { bands: ["7-9", "10-12"], setup: "What do you call a fake noodle?", punchline: "An impasta." },
  { bands: ["7-9"], setup: "Why don’t scientists trust atoms?", punchline: "Because they make up everything." },
  { bands: ["7-9", "10-12"], setup: "What did one wall say to the other?", punchline: "I’ll meet you at the corner." },
  { bands: ["7-9"], setup: "Why did the bicycle fall over?", punchline: "It was two-tired." },
  { bands: ["7-9", "10-12"], setup: "What’s orange and sounds like a parrot?", punchline: "A carrot." },
  { bands: ["7-9"], setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one." },
  { bands: ["7-9", "10-12"], setup: "How does a penguin build a house?", punchline: "Igloos it together." },
  { bands: ["7-9"], setup: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
  { bands: ["10-12"], setup: "Why can’t you hear a pterodactyl go to the bathroom?", punchline: "Because the P is silent." },
  { bands: ["10-12"], setup: "What do you call an alligator in a vest?", punchline: "An investigator." },
  { bands: ["10-12"], setup: "Why did the math book look so sad?", punchline: "It had too many problems." },
  { bands: ["10-12"], setup: "What’s the best thing about Switzerland?", punchline: "I don’t know, but the flag is a big plus." },
  { bands: ["10-12"], setup: "Why do bees have sticky hair?", punchline: "They use honeycombs." },
  { bands: ["4-6", "7-9"], setup: "What time is it when an elephant sits on your fence?", punchline: "Time to get a new fence." },
  { bands: ["4-6"], setup: "Why did the teddy bear say no to dessert?", punchline: "It was already stuffed." },
  { bands: ["7-9", "10-12"], setup: "How do you organize a space party?", punchline: "You planet." },
  { bands: ["4-6", "7-9"], setup: "What do you call a snowman in summer?", punchline: "A puddle." },
  { bands: ["7-9"], setup: "Why was the calendar always calm?", punchline: "Its days were numbered — but it kept cool." },
  { bands: ["10-12"], setup: "I told my dog we were getting a cat. Want to know his reaction?", punchline: "He was feline fine about it… after a minute." },
  { bands: ["4-6"], setup: "Knock knock. Who’s there? Lettuce.", punchline: "Lettuce in — it’s breakfast time!" },
  { bands: ["7-9", "10-12"], setup: "What’s a skeleton’s least favorite room?", punchline: "The living room." },
  { bands: ["4-6", "7-9"], setup: "Why did the tomato turn red?", punchline: "It saw the salad dressing." },
  { bands: ["10-12"], setup: "Parallel lines have so much in common.", punchline: "It’s a shame they’ll never meet." },
  { bands: ["4-6"], setup: "What do you call a dog magician?", punchline: "A labracadabrador." },
  { bands: ["4-6"], setup: "Why did the frog take the bus to work?", punchline: "His car got toad away." },
  { bands: ["4-6"], setup: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated." },
  { bands: ["4-6"], setup: "Why did the cookie feel sad?", punchline: "Its mom was a wafer too long." },
  { bands: ["4-6"], setup: "What do you call a duck that gets all A’s?", punchline: "A wise quacker." },
  { bands: ["4-6"], setup: "Why do bananas wear sunscreen?", punchline: "So they don’t peel." },
  { bands: ["4-6"], setup: "What’s a sheep’s favorite game?", punchline: "Baa-dminton." },
  { bands: ["4-6"], setup: "What do you call a bear stuck in the rain?", punchline: "A drizzly bear." },
  { bands: ["4-6"], setup: "Why did the picture go to jail?", punchline: "It was framed." },
  { bands: ["4-6"], setup: "What do you call a pig that does karate?", punchline: "A pork chop." },
  { bands: ["4-6"], setup: "Why did the orange stop rolling?", punchline: "It ran out of juice." },
  { bands: ["4-6"], setup: "What do you call a cow on a trampoline?", punchline: "A milkshake." },
  { bands: ["4-6"], setup: "Knock knock. Who’s there? Cows go.", punchline: "Cows go moo, not who!" },
  { bands: ["4-6"], setup: "What do you call a happy mushroom?", punchline: "A fun-gi." },
  { bands: ["4-6"], setup: "Why was the baby strawberry crying?", punchline: "Its parents were in a jam." },
  { bands: ["4-6"], setup: "What do you call a dinosaur that is sleeping?", punchline: "A dino-snore." },
  { bands: ["4-6"], setup: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they’d be bagels." },
  { bands: ["4-6"], setup: "What did the little corn say to the mama corn?", punchline: "Where is pop corn?" },
  { bands: ["4-6"], setup: "What do you call a boat that is shy?", punchline: "A little tug-boat." },
  { bands: ["4-6"], setup: "Why did the jelly wobble?", punchline: "It saw the trifle coming." },
  { bands: ["4-6", "7-9"], setup: "What kind of tree fits in your hand?", punchline: "A palm tree." },
  { bands: ["4-6", "7-9"], setup: "Why did the belt go to jail?", punchline: "For holding up a pair of pants." },
  { bands: ["4-6", "7-9"], setup: "What do you call a snowman with a suntan?", punchline: "A puddle." },
  { bands: ["4-6", "7-9"], setup: "How do you catch a squirrel?", punchline: "Climb a tree and act like a nut." },
  { bands: ["4-6", "7-9"], setup: "Why did the crab never share?", punchline: "Because it’s a little shellfish." },
  { bands: ["4-6", "7-9"], setup: "What do you call a lazy kangaroo?", punchline: "A pouch potato." },
  { bands: ["4-6", "7-9"], setup: "Why did the football coach go to the bank?", punchline: "To get his quarter back." },
  { bands: ["4-6", "7-9"], setup: "What do you get when you cross a snowman and a dog?", punchline: "Frostbite." },
  { bands: ["4-6", "7-9"], setup: "Why did the banana split?", punchline: "Because it saw the milkshake." },
  { bands: ["4-6", "7-9"], setup: "What do you call a droid that takes the long way around?", punchline: "R2 detour." },
  { bands: ["7-9"], setup: "Why did the computer go to the doctor?", punchline: "It caught a virus." },
  { bands: ["7-9"], setup: "What do you call a fish with no eyes?", punchline: "A fsh." },
  { bands: ["7-9"], setup: "Why did the tree go to the barber?", punchline: "It needed a trim." },
  { bands: ["7-9"], setup: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
  { bands: ["7-9"], setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
  { bands: ["7-9"], setup: "What did the ocean say to the beach?", punchline: "Nothing — it just waved." },
  { bands: ["7-9"], setup: "Why don’t oysters share their pearls?", punchline: "Because they’re shellfish." },
  { bands: ["7-9"], setup: "What do you call a magic dog?", punchline: "A labracadabrador." },
  { bands: ["7-9"], setup: "Why was the math teacher happy on the weekend?", punchline: "No pupils to divide her time." },
  { bands: ["7-9"], setup: "What do you call a can opener that doesn’t work?", punchline: "A can’t opener." },
  { bands: ["7-9"], setup: "Why did the clock get in trouble at school?", punchline: "It kept tocking." },
  { bands: ["7-9"], setup: "What do you call a boomerang that won’t come back?", punchline: "A stick." },
  { bands: ["7-9"], setup: "Why did the spider join the computer team?", punchline: "It was great at making websites." },
  { bands: ["7-9"], setup: "What do you call a sad strawberry?", punchline: "A blueberry." },
  { bands: ["7-9"], setup: "Why did the grape stop in the middle of the road?", punchline: "It ran out of juice." },
  { bands: ["7-9", "10-12"], setup: "What did the traffic light say to the car?", punchline: "Don’t look — I’m about to change." },
  { bands: ["7-9", "10-12"], setup: "Why did the coffee file a police report?", punchline: "It got mugged." },
  { bands: ["7-9", "10-12"], setup: "What do you call a pile of cats?", punchline: "A meow-ntain." },
  { bands: ["7-9", "10-12"], setup: "Why did the stadium get hot after the game?", punchline: "All the fans left." },
  { bands: ["7-9", "10-12"], setup: "What do you call a dog that can do magic tricks?", punchline: "A labracadabrador." },
  { bands: ["7-9", "10-12"], setup: "Why don’t skeletons fight each other?", punchline: "They don’t have the guts." },
  { bands: ["7-9", "10-12"], setup: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
  { bands: ["7-9", "10-12"], setup: "Why did the bread go to therapy?", punchline: "It had too much on its plate." },
  { bands: ["7-9", "10-12"], setup: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
  { bands: ["7-9", "10-12"], setup: "Why was the broom running late?", punchline: "It swept in." },
  { bands: ["10-12"], setup: "Why did the scarecrow win an award?", punchline: "He was the best in his field, hands down." },
  { bands: ["10-12"], setup: "What did the zero say to the eight?", punchline: "Nice belt." },
  { bands: ["10-12"], setup: "Why did the photon skip the hotel luggage cart?", punchline: "It was traveling light." },
  { bands: ["10-12"], setup: "Why don’t programmers like nature?", punchline: "It has too many bugs." },
  { bands: ["10-12"], setup: "What do you call a bear with no ears?", punchline: "B." },
  { bands: ["10-12"], setup: "Why did the grammar teacher love the beach?", punchline: "The tide was full of commas and pauses." },
  { bands: ["10-12"], setup: "What did one ocean say to the other ocean?", punchline: "Nothing, they just waved… tidal." },
  { bands: ["10-12"], setup: "Why did the two 4s skip lunch?", punchline: "They already 8." },
  { bands: ["10-12"], setup: "What do you call a dinosaur that crashes his car?", punchline: "A Tyrannosaurus wrecks." },
  { bands: ["10-12"], setup: "Why did the geometry student stay home?", punchline: "He was feeling a little off-square." },
  { bands: ["10-12"], setup: "What do you call cheese that’s been left out in the sun?", punchline: "A puddle of nacho business." },
  { bands: ["10-12"], setup: "Why did the electron refuse to pay for anything?", punchline: "It was negative about spending." },
  { bands: ["10-12"], setup: "What did the historian say at the party?", punchline: "It was so boring — a real thing of the past." },
  { bands: ["10-12"], setup: "Why did the comma break up with the apostrophe?", punchline: "It was too possessive." },
  { bands: ["10-12"], setup: "What do you call a well-dressed lion?", punchline: "A dandy-lion." },
  { bands: ["10-12"], setup: "Why did the volcano take a break?", punchline: "It needed to let off some steam." },
  { bands: ["10-12"], setup: "What do you get from a pampered cow?", punchline: "Spoiled milk." },
  { bands: ["10-12"], setup: "Why did the astronomer keep hitting his head?", punchline: "He kept spacing out." },
  { bands: ["4-6", "10-12"], setup: "What did the big flower say to the little flower?", punchline: "Hi, bud!" },
  { bands: ["7-9", "10-12"], setup: "Why did the golfer wear two pairs of socks?", punchline: "In case he got a hole in one." },
  { bands: ["4-6", "7-9", "10-12"], setup: "What do you call a nervous javelin thrower?", punchline: "Shakespeare." },
  { bands: ["4-6", "7-9", "10-12"], setup: "Why can’t your nose be twelve inches long?", punchline: "Because then it would be a foot." },
];

export function pickJoke(band: AgeBand, rng: () => number): JokeItem {
  const pool = JOKES.filter((j) => j.bands.includes(band));
  const j = pick(rng, pool.length ? pool : JOKES);
  return { setup: j.setup, punchline: j.punchline };
}
