import type { AgeBand } from "../types";
import { pick } from "../rng";

export interface RiddleItem {
  question: string;
  answer: string;
}

interface RiddleEntry extends RiddleItem {
  bands: AgeBand[];
}

const RIDDLES: RiddleEntry[] = [
  { bands: ["4-6"], question: "I have a face and two hands, but no arms or legs. What am I?", answer: "A clock." },
  { bands: ["4-6"], question: "What has to be broken before you can use it?", answer: "An egg." },
  { bands: ["4-6"], question: "What gets wetter the more it dries?", answer: "A towel." },
  { bands: ["4-6"], question: "I’m tall when I’m young and short when I’m old. What am I?", answer: "A candle." },
  { bands: ["4-6", "7-9"], question: "What has keys but can’t open doors?", answer: "A piano (or a computer keyboard)." },
  { bands: ["4-6"], question: "What has a head and a tail but no body?", answer: "A coin." },
  { bands: ["4-6", "7-9"], question: "What room has no doors or windows?", answer: "A mushroom." },
  { bands: ["4-6", "7-9"], question: "What can you catch but not throw?", answer: "A cold." },
  { bands: ["7-9"], question: "I speak without a mouth and hear without ears. What am I?", answer: "An echo." },
  { bands: ["7-9"], question: "The more you take, the more you leave behind. What are they?", answer: "Footsteps." },
  { bands: ["7-9", "10-12"], question: "What has cities, but no houses; forests, but no trees; water, but no fish?", answer: "A map." },
  { bands: ["7-9"], question: "What invention lets you look through a wall?", answer: "A window." },
  { bands: ["7-9", "10-12"], question: "What building has the most stories?", answer: "A library." },
  { bands: ["7-9"], question: "What goes up but never comes down?", answer: "Your age." },
  { bands: ["7-9", "10-12"], question: "I have branches, but no fruit, trunk, or leaves. What am I?", answer: "A bank." },
  { bands: ["10-12"], question: "What English word has three consecutive double letters?", answer: "Bookkeeper." },
  { bands: ["10-12"], question: "What can travel around the world while staying in a corner?", answer: "A stamp." },
  { bands: ["10-12"], question: "Forward I am heavy; backward I am not. What am I?", answer: "The word ton." },
  { bands: ["10-12"], question: "What disappears as soon as you say its name?", answer: "Silence." },
  { bands: ["10-12"], question: "I am always in front of you but can’t be seen. What am I?", answer: "The future." },
  { bands: ["4-6"], question: "What kind of key opens a banana?", answer: "A mon-key." },
  { bands: ["4-6", "7-9"], question: "What has four legs in the morning, two at noon, and three at night — wait, that’s too hard. Simpler: what has four wheels and flies?", answer: "A garbage truck." },
  { bands: ["7-9"], question: "Where does Thursday come before Wednesday?", answer: "In the dictionary." },
  { bands: ["4-6"], question: "What do you call a bear without an ear?", answer: "B." },
  { bands: ["7-9", "10-12"], question: "What runs but never walks, has a bed but never sleeps?", answer: "A river." },
  { bands: ["10-12"], question: "What begins with T, ends with T, and has T in it?", answer: "A teapot." },
  { bands: ["4-6", "7-9"], question: "If you drop me, I’m sure to crack — but give me a smile and I’ll always smile back. What am I?", answer: "A mirror." },
  { bands: ["7-9", "10-12"], question: "What has one eye but can’t see?", answer: "A needle." },
  { bands: ["4-6"], question: "What is full of holes but still holds water?", answer: "A sponge." },
  { bands: ["10-12"], question: "A cowboy rode into town on Friday. He stayed three days and left on Friday. How?", answer: "His horse was named Friday." },
  { bands: ["4-6"], question: "What animal says moo and gives us milk?", answer: "A cow." },
  { bands: ["4-6"], question: "I am yellow, I am hot, and I light up the day. What am I?", answer: "The sun." },
  { bands: ["4-6"], question: "What has wings and can fly but is not a bird?", answer: "A butterfly." },
  { bands: ["4-6"], question: "I am round, I bounce, and you kick me. What am I?", answer: "A ball." },
  { bands: ["4-6"], question: "What falls in winter, is white, and is cold?", answer: "Snow." },
  { bands: ["4-6"], question: "What has a long neck and yellow spots and is very tall?", answer: "A giraffe." },
  { bands: ["4-6"], question: "I go up and down but never move. What am I?", answer: "The stairs." },
  { bands: ["4-6"], question: "What has four legs and barks?", answer: "A dog." },
  { bands: ["4-6"], question: "I am cold and sweet and you eat me on a hot day. What am I?", answer: "Ice cream." },
  { bands: ["4-6"], question: "What has a shell and moves very slowly?", answer: "A snail (or a turtle)." },
  { bands: ["4-6"], question: "What do bees make that is sweet and golden?", answer: "Honey." },
  { bands: ["4-6"], question: "I have petals and grow in a garden. What am I?", answer: "A flower." },
  { bands: ["4-6"], question: "What lives in the water, has fins, and swims?", answer: "A fish." },
  { bands: ["4-6"], question: "I am used to sweep the floor. What am I?", answer: "A broom." },
  { bands: ["4-6"], question: "What has hands but cannot clap?", answer: "A clock." },
  { bands: ["4-6"], question: "I twinkle in the sky at night. What am I?", answer: "A star." },
  { bands: ["4-6"], question: "What is white, comes from a cow, and you pour on cereal?", answer: "Milk." },
  { bands: ["4-6"], question: "I hop and I say ribbit. What am I?", answer: "A frog." },
  { bands: ["4-6"], question: "What has a trunk but is not a car?", answer: "An elephant." },
  { bands: ["4-6"], question: "I keep your feet warm and come in pairs. What am I?", answer: "Socks." },
  { bands: ["4-6", "7-9"], question: "What has teeth but cannot bite?", answer: "A comb." },
  { bands: ["4-6", "7-9"], question: "What has a neck but no head?", answer: "A bottle." },
  { bands: ["4-6", "7-9"], question: "What can you break without touching it?", answer: "A promise." },
  { bands: ["4-6", "7-9"], question: "What has legs but cannot walk?", answer: "A table (or a chair)." },
  { bands: ["4-6", "7-9"], question: "What goes up when the rain comes down?", answer: "An umbrella." },
  { bands: ["4-6", "7-9"], question: "What is black and white and read all over?", answer: "A newspaper." },
  { bands: ["4-6", "7-9"], question: "What has ears but cannot hear?", answer: "A cornfield (an ear of corn)." },
  { bands: ["7-9"], question: "What has a thumb and four fingers but is not alive?", answer: "A glove." },
  { bands: ["7-9"], question: "What can fill a room but takes up no space?", answer: "Light." },
  { bands: ["7-9"], question: "What has many teeth but never brushes them?", answer: "A saw." },
  { bands: ["7-9"], question: "What is easy to lift but hard to throw?", answer: "A feather." },
  { bands: ["7-9"], question: "What has a bottom at the top?", answer: "Your legs." },
  { bands: ["7-9"], question: "What kind of coat is best put on wet?", answer: "A coat of paint." },
  { bands: ["7-9"], question: "What gets bigger the more you take away?", answer: "A hole." },
  { bands: ["7-9"], question: "What has words but never speaks?", answer: "A book." },
  { bands: ["7-9"], question: "What can you hold in your right hand but never in your left hand?", answer: "Your left hand." },
  { bands: ["7-9"], question: "What has a ring but no finger?", answer: "A telephone." },
  { bands: ["7-9"], question: "What flies without wings?", answer: "Time." },
  { bands: ["7-9"], question: "What has a spine but no bones?", answer: "A book." },
  { bands: ["7-9"], question: "What kind of tree can you carry in your hand?", answer: "A palm." },
  { bands: ["7-9"], question: "What has four legs but only one foot?", answer: "A bed." },
  { bands: ["7-9"], question: "What is always coming but never arrives?", answer: "Tomorrow." },
  { bands: ["7-9"], question: "What has a tongue but cannot taste?", answer: "A shoe." },
  { bands: ["7-9"], question: "What comes down but never goes up?", answer: "Rain." },
  { bands: ["7-9"], question: "What has a face and hands but no arms or legs, and hangs on a wall?", answer: "A clock." },
  { bands: ["7-9"], question: "What kind of band never plays music?", answer: "A rubber band." },
  { bands: ["7-9", "10-12"], question: "What has many keys but opens no locks and makes no music you can dance to?", answer: "A computer keyboard." },
  { bands: ["7-9", "10-12"], question: "The person who makes it sells it. The person who buys it never uses it. What is it?", answer: "A coffin." },
  { bands: ["7-9", "10-12"], question: "What can run but never walks, has a mouth but never talks?", answer: "A river." },
  { bands: ["7-9", "10-12"], question: "What has a heart that doesn't beat?", answer: "An artichoke." },
  { bands: ["7-9", "10-12"], question: "What gets sharper the more you use it?", answer: "Your brain." },
  { bands: ["7-9", "10-12"], question: "I am not alive, but I grow; I don't have lungs, but I need air. What am I?", answer: "Fire." },
  { bands: ["7-9", "10-12"], question: "What has hands but cannot hold anything?", answer: "A clock." },
  { bands: ["7-9", "10-12"], question: "What can be cracked, made, told, and played?", answer: "A joke." },
  { bands: ["7-9", "10-12"], question: "What belongs to you but is used more by others?", answer: "Your name." },
  { bands: ["7-9", "10-12"], question: "What has roots that nobody sees, and is taller than trees?", answer: "A mountain." },
  { bands: ["10-12"], question: "What five-letter word becomes shorter when you add two letters to it?", answer: "Short." },
  { bands: ["10-12"], question: "What word is spelled wrong in every dictionary?", answer: "Wrong." },
  { bands: ["10-12"], question: "What has a foot on each side and one in the middle?", answer: "A yardstick." },
  { bands: ["10-12"], question: "What can you keep after giving it to someone?", answer: "Your word." },
  { bands: ["10-12"], question: "I have keys but no locks, space but no room, and you can enter but not go inside. What am I?", answer: "A keyboard." },
  { bands: ["10-12"], question: "What has thirteen hearts but no other organs?", answer: "A deck of cards." },
  { bands: ["10-12"], question: "The more of me there is, the less you see. What am I?", answer: "Darkness." },
  { bands: ["10-12"], question: "What can point in every direction but can't reach the destination by itself?", answer: "Your finger." },
  { bands: ["10-12"], question: "What has a bark but no bite?", answer: "A tree." },
  { bands: ["10-12"], question: "What word contains all of the twenty-six letters?", answer: "Alphabet." },
  { bands: ["10-12"], question: "I fly all day but never move from my spot. What am I?", answer: "A flag." },
  { bands: ["10-12"], question: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "The letter M." },
  { bands: ["10-12"], question: "What has a bed but never sleeps and a mouth but never eats?", answer: "A river." },
  { bands: ["10-12"], question: "What starts with an E, ends with an E, but only contains one letter?", answer: "An envelope." },
  { bands: ["10-12"], question: "What goes through towns and over hills but never moves?", answer: "A road." },
  { bands: ["10-12"], question: "What can you serve but never eat?", answer: "A tennis ball (a serve)." },
  { bands: ["10-12"], question: "What is so fragile that saying its name breaks it?", answer: "Silence." },
  { bands: ["10-12"], question: "I have a golden head and a golden tail but no body. What am I?", answer: "A gold coin." },
  { bands: ["10-12"], question: "What can be measured but has no length, width, or height?", answer: "Temperature." },
  { bands: ["10-12"], question: "What English word sounds the same even after removing four of its five letters?", answer: "Queue." },
  { bands: ["10-12"], question: "What is always answered but never asks a question?", answer: "A doorbell (or a telephone)." },
  { bands: ["10-12"], question: "What can hold water even though it is full of holes?", answer: "A sponge." },
  { bands: ["10-12"], question: "I have many rings but no fingers. What am I?", answer: "A tree trunk." },
  { bands: ["10-12"], question: "What two things can you never eat for breakfast?", answer: "Lunch and dinner." },
  { bands: ["10-12"], question: "What gets broken if it is not kept?", answer: "A promise." },
  { bands: ["10-12"], question: "What kind of room can you eat?", answer: "A mushroom." },
  { bands: ["10-12"], question: "What word reads the same forwards and backwards and means a car that races?", answer: "Racecar." },
];

export function pickRiddle(band: AgeBand, rng: () => number): RiddleItem {
  const pool = RIDDLES.filter((r) => r.bands.includes(band));
  const r = pick(rng, pool.length ? pool : RIDDLES);
  return { question: r.question, answer: r.answer };
}
