import type { AgeBand } from "../types";
import { pick } from "../rng";

export interface SpanishItem {
  spanish: string;
  phonetic: string;
  english: string;
  example: string;
}

interface SpanishEntry extends SpanishItem {
  bands: AgeBand[];
}

const WORDS: SpanishEntry[] = [
  { bands: ["4-6"], spanish: "hola", phonetic: "OH-lah", english: "hello", example: "Say hola to someone at breakfast." },
  { bands: ["4-6"], spanish: "gracias", phonetic: "GRAH-see-ahs", english: "thank you", example: "Gracias for the pancakes!" },
  { bands: ["4-6"], spanish: "agua", phonetic: "AH-gwah", english: "water", example: "¿Agua, por favor?" },
  { bands: ["4-6"], spanish: "sol", phonetic: "sohl", english: "sun", example: "El sol is bright this morning." },
  { bands: ["4-6"], spanish: "gato", phonetic: "GAH-toh", english: "cat", example: "Draw a gato on the margin." },
  { bands: ["4-6", "7-9"], spanish: "amigo", phonetic: "ah-MEE-goh", english: "friend (boy)", example: "Be a good amigo today." },
  { bands: ["4-6", "7-9"], spanish: "amiga", phonetic: "ah-MEE-gah", english: "friend (girl)", example: "Invite an amiga to play." },
  { bands: ["4-6", "7-9"], spanish: "libro", phonetic: "LEE-broh", english: "book", example: "Pack one libro in your bag." },
  { bands: ["4-6", "7-9"], spanish: "casa", phonetic: "KAH-sah", english: "house / home", example: "This casa smells like toast." },
  { bands: ["4-6", "7-9"], spanish: "pan", phonetic: "pahn", english: "bread", example: "Pass the pan, please." },
  { bands: ["7-9"], spanish: "escuela", phonetic: "es-KWEH-lah", english: "school", example: "On the way to escuela, count red cars." },
  { bands: ["7-9"], spanish: "manzana", phonetic: "mahn-SAH-nah", english: "apple", example: "A manzana a day…" },
  { bands: ["7-9", "10-12"], spanish: "ventana", phonetic: "ven-TAH-nah", english: "window", example: "Look out the ventana." },
  { bands: ["7-9"], spanish: "perro", phonetic: "PEH-rroh", english: "dog", example: "The perro wants a walk." },
  { bands: ["7-9", "10-12"], spanish: "feliz", phonetic: "feh-LEES", english: "happy", example: "¡Qué día feliz!" },
  { bands: ["7-9"], spanish: "noche", phonetic: "NOH-cheh", english: "night", example: "Buenas noches later — buenos días now." },
  { bands: ["7-9", "10-12"], spanish: "estrellas", phonetic: "es-TREH-yahs", english: "stars", example: "Count estrellas after dark." },
  { bands: ["7-9", "10-12"], spanish: "camino", phonetic: "kah-MEE-noh", english: "path / road", example: "Which camino to the bus?" },
  { bands: ["10-12"], spanish: "biblioteca", phonetic: "bee-blee-oh-TEH-kah", english: "library", example: "Meet me at the biblioteca." },
  { bands: ["10-12"], spanish: "desayuno", phonetic: "deh-sah-YOO-noh", english: "breakfast", example: "Desayuno is the most important strip of the day." },
  { bands: ["10-12"], spanish: "curiosidad", phonetic: "koo-ree-oh-see-DAHD", english: "curiosity", example: "Curiosidad opens doors." },
  { bands: ["10-12"], spanish: "valiente", phonetic: "vah-lee-EN-teh", english: "brave", example: "Sé valiente with a new word." },
  { bands: ["10-12"], spanish: "tiempo", phonetic: "tee-EM-poh", english: "time / weather", example: "¿Qué tiempo hace hoy?" },
  { bands: ["10-12"], spanish: "siempre", phonetic: "see-EM-preh", english: "always", example: "Siempre try one Spanish word out loud." },
  { bands: ["4-6"], spanish: "sí", phonetic: "see", english: "yes", example: "Sí, I’ll try the new fruit." },
  { bands: ["4-6"], spanish: "no", phonetic: "noh", english: "no", example: "No means no — politely." },
  { bands: ["4-6", "7-9"], spanish: "rojo", phonetic: "ROH-hoh", english: "red", example: "Find something rojo." },
  { bands: ["4-6", "7-9"], spanish: "azul", phonetic: "ah-SOOL", english: "blue", example: "Is the sky azul today?" },
  { bands: ["7-9", "10-12"], spanish: "familia", phonetic: "fah-MEE-lee-ah", english: "family", example: "Who’s in your familia this morning?" },
  { bands: ["7-9"], spanish: "zapato", phonetic: "sah-PAH-toh", english: "shoe", example: "Find your other zapato." },
  { bands: ["10-12"], spanish: "pregunta", phonetic: "preh-GOON-tah", english: "question", example: "Ask one buena pregunta today." },
  { bands: ["4-6", "7-9"], spanish: "leche", phonetic: "LEH-cheh", english: "milk", example: "Leche in the cereal bowl." },
  { bands: ["7-9", "10-12"], spanish: "mundo", phonetic: "MOON-doh", english: "world", example: "Good morning, mundo." },
  { bands: ["10-12"], spanish: "aprender", phonetic: "ah-pren-DEHR", english: "to learn", example: "Hoy voy a aprender una palabra." },
  { bands: ["4-6"], spanish: "uno", phonetic: "OO-noh", english: "one", example: "Count uno, dos, tres to start." },
  { bands: ["4-6"], spanish: "dos", phonetic: "dohs", english: "two", example: "Hold up dos fingers." },
  { bands: ["4-6"], spanish: "tres", phonetic: "trehs", english: "three", example: "I see tres birds outside." },
  { bands: ["4-6"], spanish: "cuatro", phonetic: "KWAH-troh", english: "four", example: "There are cuatro chairs at the table." },
  { bands: ["4-6"], spanish: "cinco", phonetic: "SEEN-koh", english: "five", example: "Give me cinco — high five!" },
  { bands: ["4-6", "7-9"], spanish: "verde", phonetic: "VEHR-deh", english: "green", example: "The grass is verde." },
  { bands: ["4-6", "7-9"], spanish: "amarillo", phonetic: "ah-mah-REE-yoh", english: "yellow", example: "The sun looks amarillo." },
  { bands: ["4-6", "7-9"], spanish: "negro", phonetic: "NEH-groh", english: "black", example: "My shoes are negro." },
  { bands: ["4-6", "7-9"], spanish: "blanco", phonetic: "BLAHN-koh", english: "white", example: "The snow is blanco." },
  { bands: ["4-6"], spanish: "rosa", phonetic: "ROH-sah", english: "pink", example: "She has a rosa backpack." },
  { bands: ["4-6"], spanish: "naranja", phonetic: "nah-RAHN-hah", english: "orange", example: "Peel a naranja for a snack." },
  { bands: ["4-6"], spanish: "mamá", phonetic: "mah-MAH", english: "mom", example: "Give mamá a hug." },
  { bands: ["4-6"], spanish: "papá", phonetic: "pah-PAH", english: "dad", example: "Papá is making eggs." },
  { bands: ["4-6", "7-9"], spanish: "hermano", phonetic: "ehr-MAH-noh", english: "brother", example: "My hermano shares his toys." },
  { bands: ["4-6", "7-9"], spanish: "hermana", phonetic: "ehr-MAH-nah", english: "sister", example: "My hermana likes to draw." },
  { bands: ["4-6", "7-9"], spanish: "abuela", phonetic: "ah-BWEH-lah", english: "grandmother", example: "Abuela tells the best stories." },
  { bands: ["4-6", "7-9"], spanish: "abuelo", phonetic: "ah-BWEH-loh", english: "grandfather", example: "Abuelo waters the plants." },
  { bands: ["4-6"], spanish: "bebé", phonetic: "beh-BEH", english: "baby", example: "The bebé is taking a nap." },
  { bands: ["4-6"], spanish: "pájaro", phonetic: "PAH-hah-roh", english: "bird", example: "A pájaro is singing outside." },
  { bands: ["4-6"], spanish: "pez", phonetic: "pehs", english: "fish", example: "There's a pez in the tank." },
  { bands: ["4-6"], spanish: "vaca", phonetic: "BAH-kah", english: "cow", example: "The vaca says moo." },
  { bands: ["4-6", "7-9"], spanish: "caballo", phonetic: "kah-BAH-yoh", english: "horse", example: "Ride the caballo at the farm." },
  { bands: ["4-6"], spanish: "pato", phonetic: "PAH-toh", english: "duck", example: "The pato swims in the pond." },
  { bands: ["4-6"], spanish: "oso", phonetic: "OH-soh", english: "bear", example: "The oso likes honey." },
  { bands: ["4-6"], spanish: "conejo", phonetic: "koh-NEH-hoh", english: "rabbit", example: "The conejo hops fast." },
  { bands: ["4-6"], spanish: "luna", phonetic: "LOO-nah", english: "moon", example: "The luna is round tonight." },
  { bands: ["4-6"], spanish: "flor", phonetic: "flohr", english: "flower", example: "Pick one flor for the table." },
  { bands: ["4-6", "7-9"], spanish: "árbol", phonetic: "AHR-bohl", english: "tree", example: "A big árbol shades the yard." },
  { bands: ["4-6"], spanish: "mano", phonetic: "MAH-noh", english: "hand", example: "Raise your mano to answer." },
  { bands: ["4-6"], spanish: "pie", phonetic: "pee-EH", english: "foot", example: "My pie fits the new shoe." },
  { bands: ["4-6"], spanish: "ojo", phonetic: "OH-hoh", english: "eye", example: "Close one ojo and wink." },
  { bands: ["4-6"], spanish: "adiós", phonetic: "ah-dee-OHS", english: "goodbye", example: "Wave adiós at the door." },
  { bands: ["7-9"], spanish: "comer", phonetic: "koh-MEHR", english: "to eat", example: "Time to comer breakfast." },
  { bands: ["7-9"], spanish: "beber", phonetic: "beh-BEHR", english: "to drink", example: "Beber your milk before school." },
  { bands: ["7-9"], spanish: "correr", phonetic: "koh-RREHR", english: "to run", example: "Let's correr to the bus." },
  { bands: ["7-9"], spanish: "saltar", phonetic: "sahl-TAHR", english: "to jump", example: "Saltar over the puddle." },
  { bands: ["7-9"], spanish: "jugar", phonetic: "hoo-GAHR", english: "to play", example: "Can we jugar after school?" },
  { bands: ["7-9"], spanish: "cantar", phonetic: "kahn-TAHR", english: "to sing", example: "Cantar your favorite song." },
  { bands: ["7-9"], spanish: "bailar", phonetic: "bye-LAHR", english: "to dance", example: "Bailar in the kitchen." },
  { bands: ["7-9"], spanish: "leer", phonetic: "leh-EHR", english: "to read", example: "I like to leer at night." },
  { bands: ["7-9", "10-12"], spanish: "escribir", phonetic: "es-kree-BEER", english: "to write", example: "Escribir your name at the top." },
  { bands: ["7-9"], spanish: "dormir", phonetic: "dohr-MEER", english: "to sleep", example: "Time to dormir soon." },
  { bands: ["7-9"], spanish: "grande", phonetic: "GRAHN-deh", english: "big", example: "That's a grande sandwich." },
  { bands: ["7-9"], spanish: "pequeño", phonetic: "peh-KEH-nyoh", english: "small", example: "A pequeño puppy fits in my hands." },
  { bands: ["7-9"], spanish: "rápido", phonetic: "RRAH-pee-doh", english: "fast", example: "You're rápido today!" },
  { bands: ["7-9"], spanish: "mesa", phonetic: "MEH-sah", english: "table", example: "Set the mesa for dinner." },
  { bands: ["7-9"], spanish: "silla", phonetic: "SEE-yah", english: "chair", example: "Push in your silla." },
  { bands: ["7-9"], spanish: "puerta", phonetic: "PWEHR-tah", english: "door", example: "Close the puerta, please." },
  { bands: ["7-9"], spanish: "cama", phonetic: "KAH-mah", english: "bed", example: "Make your cama in the morning." },
  { bands: ["7-9"], spanish: "queso", phonetic: "KEH-soh", english: "cheese", example: "I want queso on my toast." },
  { bands: ["7-9"], spanish: "huevo", phonetic: "WEH-voh", english: "egg", example: "Crack one huevo for the pan." },
  { bands: ["7-9"], spanish: "fruta", phonetic: "FROO-tah", english: "fruit", example: "Pick a fruta for your lunch." },
  { bands: ["7-9"], spanish: "arroz", phonetic: "ah-RROHS", english: "rice", example: "We're having arroz tonight." },
  { bands: ["7-9"], spanish: "sopa", phonetic: "SOH-pah", english: "soup", example: "Warm sopa on a cold day." },
  { bands: ["7-9"], spanish: "día", phonetic: "DEE-ah", english: "day", example: "Have a great día!" },
  { bands: ["7-9"], spanish: "hoy", phonetic: "oy", english: "today", example: "What's the plan for hoy?" },
  { bands: ["7-9", "10-12"], spanish: "mañana", phonetic: "mah-NYAH-nah", english: "tomorrow / morning", example: "See you mañana." },
  { bands: ["7-9"], spanish: "lluvia", phonetic: "YOO-vee-ah", english: "rain", example: "Bring a coat for the lluvia." },
  { bands: ["7-9"], spanish: "nieve", phonetic: "nee-EH-veh", english: "snow", example: "Let's play in the nieve." },
  { bands: ["7-9"], spanish: "viento", phonetic: "vee-EN-toh", english: "wind", example: "The viento moved my hat." },
  { bands: ["7-9"], spanish: "nube", phonetic: "NOO-beh", english: "cloud", example: "That nube looks like a bunny." },
  { bands: ["7-9", "10-12"], spanish: "playa", phonetic: "PLAH-yah", english: "beach", example: "We built a castle at the playa." },
  { bands: ["7-9", "10-12"], spanish: "montaña", phonetic: "mohn-TAH-nyah", english: "mountain", example: "We hiked up the montaña." },
  { bands: ["7-9"], spanish: "río", phonetic: "RREE-oh", english: "river", example: "The río runs fast in spring." },
  { bands: ["7-9"], spanish: "mar", phonetic: "mahr", english: "sea", example: "Waves roll in from the mar." },
  { bands: ["7-9", "10-12"], spanish: "bonito", phonetic: "boh-NEE-toh", english: "pretty / nice", example: "What a bonito drawing!" },
  { bands: ["7-9", "10-12"], spanish: "gracioso", phonetic: "grah-see-OH-soh", english: "funny", example: "That joke was gracioso." },
  { bands: ["10-12"], spanish: "aventura", phonetic: "ah-ven-TOO-rah", english: "adventure", example: "Today is a new aventura." },
  { bands: ["10-12"], spanish: "esperanza", phonetic: "es-peh-RAHN-sah", english: "hope", example: "Keep a little esperanza." },
  { bands: ["10-12"], spanish: "sueño", phonetic: "SWEH-nyoh", english: "dream", example: "Follow your sueño." },
  { bands: ["10-12"], spanish: "recuerdo", phonetic: "rreh-KWEHR-doh", english: "memory", example: "That's a happy recuerdo." },
  { bands: ["10-12"], spanish: "naturaleza", phonetic: "nah-too-rah-LEH-sah", english: "nature", example: "Spend time in la naturaleza." },
  { bands: ["10-12"], spanish: "inteligente", phonetic: "in-teh-lee-HEN-teh", english: "smart", example: "That was an inteligente idea." },
  { bands: ["10-12"], spanish: "amable", phonetic: "ah-MAH-bleh", english: "kind", example: "Be amable to a classmate." },
  { bands: ["10-12"], spanish: "generoso", phonetic: "heh-neh-ROH-soh", english: "generous", example: "A generoso friend shares." },
  { bands: ["10-12"], spanish: "paciencia", phonetic: "pah-see-EN-see-ah", english: "patience", example: "Have a little paciencia." },
  { bands: ["10-12"], spanish: "descubrir", phonetic: "des-koo-BREER", english: "to discover", example: "We'll descubrir something new." },
  { bands: ["10-12"], spanish: "imaginar", phonetic: "ee-mah-hee-NAHR", english: "to imagine", example: "Imaginar a better ending." },
  { bands: ["10-12"], spanish: "explorar", phonetic: "eks-ploh-RAHR", english: "to explore", example: "Let's explorar the backyard." },
  { bands: ["10-12"], spanish: "corazón", phonetic: "koh-rah-SOHN", english: "heart", example: "Draw a corazón on the note." },
  { bands: ["10-12"], spanish: "fuerza", phonetic: "FWEHR-sah", english: "strength", example: "Find your fuerza today." },
  { bands: ["10-12"], spanish: "libertad", phonetic: "lee-behr-TAHD", english: "freedom", example: "Weekends feel like libertad." },
  { bands: ["10-12"], spanish: "amistad", phonetic: "ah-mees-TAHD", english: "friendship", example: "Amistad makes school fun." },
  { bands: ["7-9", "10-12"], spanish: "mariposa", phonetic: "mah-ree-POH-sah", english: "butterfly", example: "A mariposa landed on the flower." },
  { bands: ["7-9", "10-12"], spanish: "arcoíris", phonetic: "ahr-koh-EE-rees", english: "rainbow", example: "Look, an arcoíris after the rain!" },
  { bands: ["10-12"], spanish: "bosque", phonetic: "BOHS-keh", english: "forest", example: "The bosque is full of tall trees." },
  { bands: ["10-12"], spanish: "océano", phonetic: "oh-SEH-ah-noh", english: "ocean", example: "The océano is deep and blue." },
  { bands: ["10-12"], spanish: "por favor", phonetic: "pohr fah-VOHR", english: "please", example: "Ask \"por favor\" for seconds." },
  { bands: ["10-12"], spanish: "de nada", phonetic: "deh NAH-dah", english: "you're welcome", example: "Say \"de nada\" when someone thanks you." },
  { bands: ["10-12"], spanish: "buenos días", phonetic: "BWEH-nohs DEE-ahs", english: "good morning", example: "Start the day with \"buenos días!\"" },
  { bands: ["10-12"], spanish: "hasta luego", phonetic: "AHS-tah loo-EH-goh", english: "see you later", example: "Wave and say \"hasta luego.\"" },
  { bands: ["10-12"], spanish: "lo siento", phonetic: "loh see-EN-toh", english: "I'm sorry", example: "Say \"lo siento\" if you bump someone." },
];

export function pickSpanish(band: AgeBand, rng: () => number): SpanishItem {
  const pool = WORDS.filter((w) => w.bands.includes(band));
  const w = pick(rng, pool.length ? pool : WORDS);
  return {
    spanish: w.spanish,
    phonetic: w.phonetic,
    english: w.english,
    example: w.example,
  };
}
