import json, math, csv
gj=json.load(open('/tmp/us-states.json'))
feat={f['properties']['name']:f['geometry'] for f in gj['features']}
caps={}
with open('/tmp/caps.csv') as fh:
    for row in csv.DictReader(fh):
        caps[row['name']]=(row['description'], float(row['latitude']), float(row['longitude']))

def rings(geom):
    polys=[geom['coordinates']] if geom['type']=='Polygon' else geom['coordinates']
    return [poly[0] for poly in polys]  # exterior rings

def area(ring):
    a=0
    for i in range(len(ring)-1):
        x1,y1=ring[i]; x2,y2=ring[i+1]
        a+=x1*y2-x2*y1
    return abs(a)/2

def rdp(pts, eps):
    if len(pts)<3: return pts
    def d(p,a,b):
        (x,y),(x1,y1),(x2,y2)=p,a,b
        dx,dy=x2-x1,y2-y1
        if dx==dy==0: return math.hypot(x-x1,y-y1)
        t=((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)
        t=max(0,min(1,t)); px,py=x1+t*dx,y1+t*dy
        return math.hypot(x-px,y-py)
    dmax,idx=0,0
    for i in range(1,len(pts)-1):
        dd=d(pts[i],pts[0],pts[-1])
        if dd>dmax: dmax,idx=dd,i
    if dmax>eps:
        return rdp(pts[:idx+1],eps)[:-1]+rdp(pts[idx:],eps)
    return [pts[0],pts[-1]]

TARGET=300.0
out=[]
STATES=[s for s in caps.keys()]  # 50 states from capitals csv
for name in STATES:
    if name not in feat: 
        raise SystemExit("missing geom "+name)
    rs=rings(feat[name])
    areas=[area(r) for r in rs]
    maxA=max(areas)
    keep=[r for r,a in zip(rs,areas) if a>=0.08*maxA]
    allpts=[p for r in keep for p in r]
    midlat=sum(p[1] for p in allpts)/len(allpts)
    k=math.cos(math.radians(midlat))
    xs=[p[0]*k for p in allpts]; ys=[p[1] for p in allpts]
    minx,maxx,miny,maxy=min(xs),max(xs),min(ys),max(ys)
    dx,dy=maxx-minx,maxy-miny
    s=TARGET/max(dx,dy)
    W=round(dx*s,1); H=round(dy*s,1)
    def tf(lon,lat): return (round((lon*k-minx)*s,1), round((maxy-lat)*s,1))
    subpaths=[]
    for r in keep:
        proj=[tf(p[0],p[1]) for p in r]
        simp=rdp(proj, 1.1)
        if len(simp)<3: continue
        d="M "+" ".join(f"{x} {y}" for x,y in simp)+" Z"
        subpaths.append(d)
    path=" ".join(subpaths)
    capname,clat,clon=caps[name]
    star=list(tf(clon,clat))
    out.append(dict(name=name,capital=capname,path=path,star=star,w=W,h=H))

# emit TS
lines=["// AUTO-GENERATED by scripts (US Census-ish outlines + capital coords).",
       "// 50 states: simplified outline path + capital star, normalized per state.",
       "export interface StateShape { name: string; capital: string; path: string; star: [number, number]; w: number; h: number; }",
       "export const US_STATES: StateShape[] = ["]
for o in out:
    lines.append(f'  {{ name: {json.dumps(o["name"])}, capital: {json.dumps(o["capital"])}, w: {o["w"]}, h: {o["h"]}, star: [{o["star"][0]}, {o["star"][1]}], path: {json.dumps(o["path"])} }},')
lines.append("];")
open('src/lib/puzzles/states-data.ts','w').write("\n".join(lines)+"\n")
import os
print("states:",len(out),"file bytes:",os.path.getsize('src/lib/puzzles/states-data.ts'))
# quick sanity: avg path length
print("avg path chars:",round(sum(len(o['path']) for o in out)/len(out)))
